In [1]:
import numpy as np

Simulate coin flip 4 times, find probability of getting 4 heads.

In [2]:
np.random.rand()

0.5828654562444284

In [3]:
np.random.rand(5)

array([0.74628554, 0.5222354 , 0.81215308, 0.93150548, 0.0294555 ])

In [4]:
np.random.rand(5,2)

array([[0.05621773, 0.63556573],
       [0.83406725, 0.06895946],
       [0.47271697, 0.42368752],
       [0.45684231, 0.88668365],
       [0.78701756, 0.89706864]])

In [8]:
np.random.seed(42)
random_numbers = np.random.rand(4)
random_numbers

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [9]:
heads = random_numbers < 0.5
heads

array([ True, False, False, False])

In [10]:
np.sum(heads)

1